-------------------------
-- English Localization String resources
-- Huami Co, ltd. (2014)
-- Herbert dai
-- 20140731
-------------------------
localization_English_table = {
    calories_table={

    },

    ok='OK',

    hour='hrs',
    minute='min',
    month='month',
    day='day',
    step="step",
    km='KM',
    minute_format='%d min',
    hour_minute_format='%d hrs %d min',
    hour_format='%d hrs',

    welcome_use="Hello, I am your Mi Band.",
    last_week_walked_format='Last week, you walked %d steps.',
    last_week_walked_info_format='Walked %d km, burned %d cal.',
    last_month_walked_format='Last month, you walked %d steps.',
    last_month_walked_info_format='Walked %d km, burned %d cal.',

    get_over_format=", about %d gram of fat.",
    click_to_get_help="Find out more to do with Mi Band.",
    take_a_walk="Take a walk with Mi Band.",
    take_a_walk_info="Mi Band will track your activities and help you to be healthier.",
    unlock_hint="Unlock phone with your Mi Band",
    unlock_hint_info="say Goodbye to the old times.",
    no_data_hint_0="Keep moving, make sports a part of your life.",
    no_data_hint_1="Want to stay happy? Just run.",
    no_data_hint_2="Cardio workout will make you light and fresh every day! ",
    no_data_hint_3="A normal adult spends 15%-20% of total sleep time in deep sleep stage. ",
    not_binded_hint="You haven’t linked any Mi Band to this account, please link one now. ",
    new_record_info="WoW! You just broke a record in walking.",
    new_record_format="New record, %d steps, %s %d",
    today_goal_reached="Congrats! You have achieved your goal today. ",
    week_continue_reach_goal="You have achieved your goal every day for an entire week! What an awesome week!",
    challenge_format="You have achieved your goal for %d days!",
    personal_best_format="Your highest record is %d days!",
    active_time_format_0="%d hr",
    active_time_format_1="%d hr",
    active_time_format_2="%d hr %d min",
    activie_run_format_0="Ran %s. Good job!",
    activie_run_format_1="Ran %s. You are doing fantastic!",
    activie_run_format_2="Ran %s, Incredible endurance!",
    activie_run_consumed="Burned %d cal. %s",

    get_distance_format=", a total of %d m.",
    activity_walk_format="%s Walked %d steps %s",
    activity_walk_consumed_format="Burned %d cal %s",

    activity_activity_format="%s %s work out%s",
    last_night_sleeped_good_format="Last night, you slept for %d hr %d min. What a great sleep!",
    last_night_sleeped_normal_format="Last night, you slept for %d hr %d min.",
    deep_sleep_format="Deep sleep stage was %d hr %d min.",

    battery_low_info="Low in battery, please charge your Mi Band.",
    battery_very_low_info="Connect to power",

    cannot_find_bracelet="Unable to find your Mi Band?",
    cannot_find_bracelet_info="Please make sure your Mi Band has power and stays nearby your phone.",

    challenge_to_get="%s days from making a new record!",
    record_reach_max="You have hit your highest record!",
    new_record_born="New record!",
 }

localization_French_table = {
    calories_table={
        {str="≈1 duo d'oeufs durs",	calories=96},
        {str="≈1 tranche de pain",	calories=100},
        {str="≈1 canette de thé glacé",	calories=112},
        {str="≈1 omelette",	calories=118},
        {str="≈2 brochettes",	calories=124},
        {str="≈1 canette de Coca-Cola",	calories=153},
        {str="≈3 brochettes",	calories=186},
        {str="≈2 duo d'oeufs durs",	calories=192},
        {str="≈2 tranches de pain",	calories=200},
        {str="≈1 bol de riz",	calories=210},
        {str="≈1 pain",	calories=221},
        {str="≈1 paquet de dragibus",	calories=223},
        {str="≈2 canettes de thé glacé",	calories=224},
        {str="≈1 petite frite",	calories=224},
        {str="≈1 tartelette",	calories=224},
        {str="≈2 omelettes",	calories=236},
        {str="≈4 brochettes",	calories=248},
        {str="≈1 hamburger",	calories=260},
        {str="≈1 beignet",	calories=270},
        {str="≈1 petit pain de viande",	calories=272},
        {str="≈3 duo d'oeufs durs",	calories=288},
        {str="≈1 cône",	calories=290},
        {str="≈3 tranches de pain",	calories=300},
        {str="≈2 canettes de Coca-Cola",	calories=306},
        {str="≈1 moyenne frite",	calories=328},
        {str="≈3 omelettes",	calories=354},
        {str="≈1 tartelette aux œufs",	calories=375},
        {str="≈4 tranches de pain",	calories=400},
        {str="≈1 grande frite",	calories=402},
        {str="≈2 bols de riz",	calories=420},
        {str="≈2 pains",	calories=442},
        {str="≈2 paquet de dragibus",	calories=446},
        {str="≈2 tartelettes",	calories=448},
        {str="≈1 paquet de nouilles instantanées",	calories=470},
        {str="≈5 tranches de pain",	calories=500},
        {str="≈1 assiette de riz frit",	calories=516},
        {str="≈2 hamburgers",	calories=520},
        {str="≈2 beignets",	calories=540},
        {str="≈2 petits pains de viande",	calories=544},
        {str="≈2 cônes",	calories=580},
        {str="≈1 bol de nouilles instantanées",	calories=581},
        {str="≈1 bol de nouilles au boeuf",	calories=593},
        {str="≈10 brochettes",	calories=620},
        {str="≈3 bols de riz",	calories=630},
        {str="≈3 pains",	calories=663},
        {str="≈2 tartelettes aux œufs",	calories=750},
        {str="≈3 beignets",	calories=810},
        {str="≈3 petits pains de viande",	calories=816},
    },

    ok='OK',

    hour='h',
    minute='min',
    month='mois',
    day='jour',
    step="pas",
    km='KM',
    minute_format='%dmin',
    hour_minute_format='%dh%dmin',
    hour_format='%dh',

    welcome_use="Salut, je suis ton Mi Band.",
    last_week_walked_format='La semaine dernier, tu as marché %d pas.',
    last_week_walked_info_format='%d km parcourus, %d cal. brûlées',
    last_month_walked_format='Le mois dernier, tu as marché %d pas.',
    last_month_walked_info_format='%d km parcourus, %d cal. brûlées',

    get_over_format=", environ %d gr de graisse.",
    click_to_get_help="Comment mieux utiliser le Mi Band.",
    take_a_walk="Va faire un tour avec Mi Band.",
    take_a_walk_info="Mi Band suivra ton activité et t'aidera à être en meilleur santé.",
    unlock_hint="Dévérouiller le téléphone avec votre Mi Band",
    unlock_hint_info="Dis au revoir au temps d'avant.",
    no_data_hint_0="Continuer de bouger, fais du sport une partie de ta vie.",
    no_data_hint_1="Tu veux rester heureux? Alors cours.",
    no_data_hint_2="L'entrainement cardio te rendra léger et frais chaque jour! ",
    no_data_hint_3="Un adulte normal passe 15%-20% de son temps de sommeil en phase de sommeil profond. ",
    not_binded_hint="Aucun Mi Band n'est associé à ce compte, en appairer un. ",
    new_record_info="WoW! Tu viens d'exploser un record en marchant.",
    new_record_format="Nouveau record, %d pas, %s %d",
    today_goal_reached="Félicitation! You have achieved your goal today. ",
    week_continue_reach_goal="Tu as atteint ton objectif chaque jour de cette semaine! Quelle semaine incroyable!",
    challenge_format="Tu as atteint ton objectif %d jours d'affilé!",
    personal_best_format="Ton meilleur record est %d jours!",
    active_time_format_0="%dh",
    active_time_format_1="%dh",
    active_time_format_2="%dh%dmin",
    activie_run_format_0="Couru %s. Bon boulot!",
    activie_run_format_1="Couru %s. Tu fais des micracles!",
    activie_run_format_2="Couru %s. Incroyable endurance!",
    activie_run_consumed="%d cal brûlées. %s",

    get_distance_format=", pour un total de %dm.",
    activity_walk_format="%s a marché %d pas %s",
    activity_walk_consumed_format="%d cal brûlées %s",

    activity_activity_format="%s %s d'entrainement %s",
    last_night_sleeped_good_format="La nuit dernière, tu as dormi %dh%dmin. Quelle bonne nuit!",
    last_night_sleeped_normal_format="La nuit dernière, tu as dormi %dh%dmin.",
    deep_sleep_format="En phase de sommeil profond pendant %dh%dmin.",

    battery_low_info="Batterie faible, branche ton Mi Band.",
    battery_very_low_info="Brancher au secteur",

    cannot_find_bracelet="Impossible de trouver ton Mi Band?",
    cannot_find_bracelet_info="Assure toi que ton Mi Band soit chargé et proche du téléphone.",

    challenge_to_get="A %s jours de battre un nouveau record!",
    record_reach_max="Tu as atteint ton meilleur record!",
    new_record_born="Nouveau record!",
 }
 
localization_Spanish_table = {
    calories_table={

    },

    ok='OK',

    hour='horas',
    minute='min',
    month='mes',
    day='día',
    step="paso",
    km='Km',
    minute_format='%d min',
    hour_minute_format='%d horas %d min',
    hour_format='%d horas',

    welcome_use="Hola, soy su MiBand.",
    last_week_walked_format='En la última semana ha dado %d pasos.',
    last_week_walked_info_format='Ha andado %d Kms, quemadas %d kcal.',
    last_month_walked_format='En el último mes ha dado %d pasos.',
    last_month_walked_info_format='Ha andado %d Kms, quemadas %d kcal.',

    get_over_format=", sobre %d gramos de grasa.",
    click_to_get_help="Descubra más cosas que hacer con su MiBand.",
    take_a_walk="Dé un paseo con MiBand.",
    take_a_walk_info="MiBand realizará un seguimiento de sus actividades y le ayudará a ser más saludable.",
    unlock_hint="Desbloquee el teléfono con su MiBand,",
    unlock_hint_info="Diga adiós al pasado.",
    no_data_hint_0="Siga moviéndose, haga el deporte una parte de su vida.",
    no_data_hint_1="¿Quiere estar feliz? Haga deporte.",
    no_data_hint_2="¡Una sesión de cardio le dejará como nuevo cada día! ",
    no_data_hint_3="Un adulto normal emplea un 15%-20% del tiempo de sueño en una fase de sueño profundo. ",
    not_binded_hint="No ha enlazado ninguna MiBand a esta cuenta, por favor enlace una ahora. ",
    new_record_info="¡Vaya! Acaba de batir un récord.",
    new_record_format="Nuevo récord, %d pasos, %s %d",
    today_goal_reached="¡Enhorabuena! Ha logrado su objetivo de hoy. ",
    week_continue_reach_goal="¡Ha alcanzado su meta todos los días durante una semana! ¡Bien hecho!",
    challenge_format="¡Ha alcanzado su meta durante %d día(s)!",
    personal_best_format="¡Su récord más alto es de %d día(s)!",
    active_time_format_0="%d hora",
    active_time_format_1="%d hora",
    active_time_format_2="%d hora %d min",
    activie_run_format_0="Ha corrido %s. ¡Buen trabajo!",
    activie_run_format_1="Ha corrido %s. ¡Lo está haciendo fenomenal!",
    activie_run_format_2="Ha corrido %s, ¡Vaya resistencia!",
    activie_run_consumed="Ha quemado %d kcal. %s",

    get_distance_format=", con un total de %d m.",
    activity_walk_format="%s Ha caminado %d pasos %s",
    activity_walk_consumed_format="Quemadas %d kcal %s",

    activity_activity_format="%s Ha hecho %s %s",
    last_night_sleeped_good_format="En la última noche ha dormido durante %d horas %d min. ¡Que gran sueño!",
    last_night_sleeped_normal_format="En la última noche ha dormido durante %d horas %d min.",
    deep_sleep_format="La fase de sueño profundo ha sido de %d horas %d min.",

    battery_low_info="Batería baja. Por favor, cargue su MiBand.",
    battery_very_low_info="Conectar a la red",

    cannot_find_bracelet="¿Incapaz de encontrar su MiBand?",
    cannot_find_bracelet_info="Por favor, asegúrese de que su MiBand está encendida y se encuentra cerca de su teléfono.",
	
	challenge_to_get="%s días después de hacer un nuevo récord!",
    record_reach_max="¡Ha alcanzado su mayor récord!",
    new_record_born="¡Nuevo récord!",
 }

localization_Croatian_table = {
	calories_table={
	
	},
	
	ok='U redu',
	
	hour='sati',
	minute='min',
	month='mjesec',
	day='dan',
	step="korak",
	km='KM',
	minute_format='%d min',
	hour_minute_format='%d sati %d min',
	hour_format='%d sati',
	
	welcome_use="Pozdrav, Ja sam tvoj Mi Band.",
	last_week_walked_format='Prošli tjedan, prohodali ste %d koraka.',
	last_week_walked_info_format='Prohodano %d km, potrošeno %d kal.',
	last_month_walked_format='Prošli mjesec, prohodali ste %d koraka.',
	last_month_walked_info_format='Prohodano %d km, potrošeno %d kal.',
	
	get_over_format=", O %d grama ili masti.",
	click_to_get_help="Saznajte što sve možete s Mi Band.",
	take_a_walk="Prošetajte s Mi Band.",
	take_a_walk_info="Mi Band će pratiti vaše aktivnosti i pomoći vam da se osjećate zdravije.",
	unlock_hint="Otključajte telefon vašim Mi Band,",
	unlock_hint_info="recite \"Zbogom\" starim vremenima.",
	no_data_hint_0="Nastavite se kretati, neka sport postane dijelom vašeg života.",
	no_data_hint_1="Želite oststi sretni? Samo trčite.",
	no_data_hint_2="Kardio vježba će vam omogućiti da se osjećate laganije i svježe svaki dan! ",
	no_data_hint_3="Normalna odrasla troši 15% -20% ukupnog vremena sna u dubokoj fazi sna. ",
	not_binded_hint="Nijedan Mi Band nije povezan na ovaj račun, povežite jedan sada. ",
	new_record_info="WoW! Oborili ste rekord u hodanju.",
	new_record_format="Novi rekord, %d koraka, %s %d",
	today_goal_reached="Čestitke! Postigli ste danjašnji cilj. ",
	week_continue_reach_goal="Postigli ste cilj svakog dana ovog tjedna! Stvarno fantastičan tjedan!",
	challenge_format="Postigli ste svoj cilj za %d dan(a)!",
	personal_best_format="Vaš najveći rekord je %d dan(a)!",
	active_time_format_0="%d sati",
	active_time_format_1="%d sati",
	active_time_format_2="%d sati %d min",
	activie_run_format_0="Trčano %s. Dobro je!",
	activie_run_format_1="Trčano %s. Ide vam fantastično!",
	activie_run_format_2="Trčano %s, Nevjerojatno ste izdržljivi!",
	activie_run_consumed="Potrošeno %d kal. %s",
	
	get_distance_format=", ukupno od %d m.",
	activity_walk_format="%s Prohodano %d koraka %s",
	activity_walk_consumed_format="Potrošeno %d kal %s",
	
	activity_activity_format="%s Napravljeno %s %s",
	last_night_sleeped_good_format="Prošle noći ste spavali %d sati %d min. Sad ste stvarno naspavani!",
	last_night_sleeped_normal_format="Prošle noći ste spavali %d sati %d min.",
	deep_sleep_format="Faza dubokog sna je bila %d sati %d min.",
	
	battery_low_info="Slaba baterija, stavite Mi Band na punjenje.",
	battery_very_low_info="Priključite na punjač",
	
	cannot_find_bracelet="Ne možete pronaći svoj Mi Band?",
	cannot_find_bracelet_info="Uvjerite se da vaš MiBand ima energije i nalazi se u blizini vašeg telefona.",
	
	challenge_to_get="%s dana od postizanja novog rekorda!",
	record_reach_max="Postigli ste svoj najveći novi rekord!",
	new_record_born="Novi rekord!",
 }

localization_Russian_table = {
    calories_table={

    },

    ok='ОК',

    hour='ч',
    minute='мин',
    month='мес.',
    day='дней',
    step="шагов",
    km='км',
    minute_format='%d мин',
    hour_minute_format='%d ч %d мин',
    hour_format='%d ч',

    welcome_use="Привет, Я твой Mi Band.",
    last_week_walked_format='Ты прошел %d шагов на прошлой неделе.',
    last_week_walked_info_format='Пройдено %d км, сожжено %d ккал.',
    last_month_walked_format='Ты прошел %d шагов в прошлом месяце.',
    last_month_walked_info_format='Пройдено %d км, сожжено %d ккал.',

    get_over_format=", приблизительно %d грамм жира.",
    click_to_get_help="Узнай, что ты можешь делать с Mi Band.",
    take_a_walk="Пройдись с Mi Band.",
    take_a_walk_info="Mi Band будет отслеживать твою активность и поможет быть здоровым.",
    unlock_hint="Разблокируй телефон с помощью Mi Band",
    unlock_hint_info="Попрощайся с дневной рутиной.",
    no_data_hint_0="Двигайся, сделай спорт частью твоей жизни.",
    no_data_hint_1="Хочешь быть счастливым? Бегай.",
    no_data_hint_2="Кардио тренировки сделают тебя бодрым и энергичным на весь день!",
    no_data_hint_3="Взрослый человек находится в стадии глубокого сна примерно 15%-20% на протяжении всего сна.",
    not_binded_hint="Ты не подключил Mi Band к этому аккаунту, пожалуйста подключить браслет.",
    new_record_info="Ого! Ты только что побил рекорд в ходьбе!",
    new_record_format="Новый рекорд, %d шагов, %s %d",
    today_goal_reached="Поздравляю! Ты достиг заданной цели сегодня.",
    week_continue_reach_goal="Ты достигал заданной цели каждый день на протяжении всей недели! Какая чудесная неделя!",
    challenge_format="Ты достигал заданной цели на протяжении %d дней!",
    personal_best_format="Твой лучший рекорд - %d дней!",
    active_time_format_0="%d ч",
    active_time_format_1="%d ч",
    active_time_format_2="%d ч %d мин",
    activie_run_format_0="Пробежал %s. Отличная работа!",
    activie_run_format_1="Пробежал %s. Супер результат!",
    activie_run_format_2="Пробежал %s, Нереальная выносливость, ты молодец!",
    activie_run_consumed="Сжег %d ккал. %s",

    get_distance_format=", всего %d м.",
    activity_walk_format="%s Пройдено %d шагов %s",
    activity_walk_consumed_format="Сжег %d ккал %s",

    activity_activity_format="%s %s тренировка%s",
    last_night_sleeped_good_format="Прошлой ночью ты спал %d ч %d мин. Какой чудесный сон!",
    last_night_sleeped_normal_format="Прошлой ночью ты спал %d ч %d мин.",
    deep_sleep_format="В стадии глубокого сна ты находился %d ч %d мин.",

    battery_low_info="Низкий заряд, зарядите Mi Band.",
    battery_very_low_info="Подключите к зарядному устройству",

    cannot_find_bracelet="Не удалось найти ваш Mi Band?",
    cannot_find_bracelet_info="Убедитесь в том, что Mi Band находится близко к телефону.",

    challenge_to_get="%s дней с момента нового рекорда!",
    record_reach_max="Ты побил свой рекорд!",
    new_record_born="Новый рекорд!",
 }
